declare module "@locale/*";
declare module "@assets/*";
declare module "@hooks/*";
declare module "@pages/*";
declare module "@components/*";
declare module "@utils/*";
declare module "@layouts/*";
declare module "@context/*";
declare module "@app-types/*";
